name: Deploy to Local Machine

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: local-ubuntu # local runner
    env:
      HTTP_HOST: ${{ secrets.HTTP_HOST }}
      HTTP_PORT: ${{ secrets.HTTP_PORT }}
      AUTH_HOST: ${{ secrets.AUTH_HOST }}
      AUTH_PORT: ${{ secrets.AUTH_PORT }}
      CATALOG_HOST: ${{ secrets.CATALOG_HOST }}
      CATALOG_PORT: ${{ secrets.CATALOG_PORT }}
      GATEWAY_HOST: ${{ secrets.GATEWAY_HOST }}
      GATEWAY_PORT: ${{ secrets.GATEWAY_PORT }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      # Make sure pnpm is installed
      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 11

      - name: Copy source files to deploy folder
        run: |
          mkdir -p ~/juicify-deploy/gateway
          rsync -vrax --delete --exclude='node_modules' ./ ~/juicify-deploy/gateway/
          cd ~/juicify-deploy/gateway

      # Install dependencies
      - name: Install dependencies
        run: |
          pnpm store prune
          cd ~/juicify-deploy/gateway
          pnpm install --frozen-lockfile
          pnpm update @juice11-micro/contracts

      # Compile code
      - name: Build application
        run: |
          cd ~/juicify-deploy/gateway
          pnpm build

      # Start application with pm2
      - name: Start/Restart Application
        run: |
          cd ~/juicify-deploy/gateway
          pm2 restart "juicify-gateway" --update-env || pm2 start dist/main.js --name "juicify-gateway"
